# Generated by Django 4.1.3 on 2022-12-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('año_de_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('pais', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('año_de_publicacion', models.DateField()),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('codigo_postal', models.IntegerField()),
                ('ciudad', models.CharField(max_length=10)),
                ('numero_de_sucursal', models.IntegerField()),
            ],
        ),
    ]
